import { obs, type AuditContext, type ObservationDraft } from '../types';
import { parsePage } from '../page';

const G = 'availability' as const;

const HOLDING_PHRASES = [
  'coming soon',
  'under construction',
  'site is under construction',
  'website coming soon',
  'launching soon',
  'opening soon',
  'we are working on it',
  'be right back',
  'this site is temporarily unavailable',
];

const PARKED_MARKERS = [
  'this domain is for sale',
  'buy this domain',
  'domain parking',
  'parked free, courtesy of',
  'this webpage was generated by the domain owner',
  'related searches',
];

const DIRECTORY_INDEX_MARKERS = ['index of /', '<title>index of', 'parent directory'];

export async function runAvailability(ctx: AuditContext): Promise<ObservationDraft[]> {
  const out: ObservationDraft[] = [];
  const root = ctx.root;
  const url = ctx.targetUrl;

  // --- Reachability ---------------------------------------------------------
  if (root.error) {
    const { kind, message } = root.error;
    if (kind === 'dns') {
      out.push(
        obs.issue(G, 'dns.resolves', `The hostname did not resolve to an address. ${message}`, {
          url,
          rawValue: { errorKind: kind },
          evidence: [{ kind: 'http_response', sourceUrl: url, content: message }],
        }),
      );
      return out; // Nothing further can be measured.
    }
    if (kind === 'robots') {
      out.push(
        obs.unverifiable(G, 'http.status', message, {
          url,
          rawValue: { errorKind: kind },
        }),
      );
      return out;
    }
    if (kind === 'timeout' || kind === 'connection') {
      out.push(
        obs.issue(G, 'http.reachable', `The site did not return a response. ${message}`, {
          url,
          rawValue: { errorKind: kind, elapsedMs: root.elapsedMs },
          evidence: [{ kind: 'http_response', sourceUrl: url, content: message }],
        }),
      );
      return out;
    }
    if (kind === 'redirect_loop') {
      out.push(
        obs.issue(G, 'redirect.loop', message, {
          url,
          rawValue: { chain: root.redirectChain },
          evidence: [
            {
              kind: 'redirect_chain',
              sourceUrl: url,
              content: root.redirectChain.map((h) => `${h.status} ${h.url}`).join('\n'),
            },
          ],
        }),
      );
      return out;
    }
    out.push(obs.unverifiable(G, 'http.status', message, { url }));
    return out;
  }

  out.push(
    obs.pass(G, 'dns.resolves', 'The hostname resolved and a connection was established.', {
      url,
    }),
  );

  // --- Status ---------------------------------------------------------------
  const statusEvidence = [
    {
      kind: 'http_response' as const,
      sourceUrl: root.finalUrl,
      content: `HTTP ${root.status}\ncontent-type: ${root.contentType ?? 'unknown'}\nserver: ${root.headers['server'] ?? 'not disclosed'}\nbytes: ${root.bytes}`,
    },
  ];

  if (root.status >= 500) {
    out.push(
      obs.issue(G, 'http.status', `The home page returned HTTP ${root.status} (server error).`, {
        url: root.finalUrl,
        rawValue: { status: root.status },
        evidence: statusEvidence,
      }),
    );
  } else if (root.status >= 400) {
    out.push(
      obs.issue(G, 'http.status', `The home page returned HTTP ${root.status}.`, {
        url: root.finalUrl,
        rawValue: { status: root.status },
        evidence: statusEvidence,
      }),
    );
  } else if (root.status >= 200 && root.status < 300) {
    out.push(
      obs.pass(G, 'http.status', `The home page returned HTTP ${root.status}.`, {
        url: root.finalUrl,
        rawValue: { status: root.status },
        evidence: statusEvidence,
      }),
    );
  } else {
    out.push(
      obs.info(G, 'http.status', `The home page returned HTTP ${root.status}.`, {
        url: root.finalUrl,
        rawValue: { status: root.status },
      }),
    );
  }

  // --- HTTPS ----------------------------------------------------------------
  const finalIsHttps = root.finalUrl.startsWith('https://');
  if (finalIsHttps) {
    out.push(
      obs.pass(G, 'https.available', 'The site is served over HTTPS.', { url: root.finalUrl }),
    );
  } else {
    // Confirm HTTPS really is unavailable before reporting it as an issue.
    const httpsUrl = root.finalUrl.replace(/^http:/, 'https:');
    const probe = await ctx.fetch(httpsUrl);
    if (probe && !probe.error && probe.status < 400) {
      out.push(
        obs.issue(
          G,
          'https.redirect',
          'HTTPS is available but visitors arriving over HTTP are not redirected to it.',
          {
            url: root.finalUrl,
            rawValue: { httpFinalUrl: root.finalUrl, httpsStatus: probe.status },
            evidence: [
              {
                kind: 'http_response',
                sourceUrl: httpsUrl,
                content: `HTTP request ended at ${root.finalUrl}\nHTTPS request returned ${probe.status}`,
              },
            ],
          },
        ),
      );
    } else if (probe) {
      out.push(
        obs.issue(G, 'https.available', 'The site could not be reached over HTTPS.', {
          url: httpsUrl,
          rawValue: { error: probe.error?.message ?? `status ${probe.status}` },
          evidence: [
            {
              kind: 'http_response',
              sourceUrl: httpsUrl,
              content: probe.error?.message ?? `HTTP ${probe.status}`,
            },
          ],
        }),
      );
    } else {
      out.push(
        obs.unverifiable(G, 'https.available', 'The crawl budget was exhausted before HTTPS could be checked.', {
          url: httpsUrl,
        }),
      );
    }
  }

  // --- TLS ------------------------------------------------------------------
  if (finalIsHttps) {
    // The runtime fetch API does not expose the peer certificate. Rather than
    // infer an expiry date we would not have measured, record it as a check the
    // engine cannot perform and let an analyst confirm it.
    out.push(
      obs.unverifiable(
        G,
        'tls.certificate',
        'Certificate details are not exposed by the HTTP client. The connection itself succeeded, which means the certificate was accepted at request time; expiry date requires manual confirmation.',
        { url: root.finalUrl },
      ),
    );
  }

  // --- Redirect chain -------------------------------------------------------
  const hops = root.redirectChain.length;
  if (hops > 3) {
    out.push(
      obs.issue(G, 'redirect.chain', `Reaching the home page required ${hops} requests.`, {
        url,
        rawValue: { hops, chain: root.redirectChain },
        evidence: [
          {
            kind: 'redirect_chain',
            sourceUrl: url,
            content: root.redirectChain.map((h) => `${h.status} ${h.url}`).join('\n'),
          },
        ],
      }),
    );
  } else if (hops > 1) {
    out.push(
      obs.info(G, 'redirect.chain', `The home page was reached after ${hops - 1} redirect(s).`, {
        url,
        rawValue: { hops, chain: root.redirectChain },
      }),
    );
  }

  // --- Page character -------------------------------------------------------
  const parsed = parsePage(root);
  const haystack = `${root.html ?? ''}`.toLowerCase();
  const visible = (parsed?.text ?? '').toLowerCase();

  if (DIRECTORY_INDEX_MARKERS.some((m) => haystack.includes(m))) {
    out.push(
      obs.issue(
        G,
        'dir.index',
        'The server returned a directory listing rather than a web page.',
        {
          url: root.finalUrl,
          rawValue: { title: parsed?.title ?? null },
          evidence: [
            {
              kind: 'html_snippet',
              sourceUrl: root.finalUrl,
              content: (root.html ?? '').slice(0, 800),
            },
          ],
        },
      ),
    );
  }

  if (PARKED_MARKERS.some((m) => visible.includes(m))) {
    out.push(
      obs.issue(G, 'page.parked', 'The home page shows domain parking or for-sale content.', {
        url: root.finalUrl,
        evidence: [
          { kind: 'html_snippet', sourceUrl: root.finalUrl, content: visible.slice(0, 600) },
        ],
      }),
    );
  } else {
    const matched = HOLDING_PHRASES.find((p) => visible.includes(p));
    // A holding page is short AND dominated by the phrase - a footer mention of
    // "coming soon" on a full site is not a holding page.
    if (matched && visible.length < 1200) {
      out.push(
        obs.issue(
          G,
          'page.holding',
          `The home page appears to be a holding page. The visible text is short and contains "${matched}".`,
          {
            url: root.finalUrl,
            rawValue: { visibleLength: visible.length, phrase: matched },
            evidence: [
              { kind: 'html_snippet', sourceUrl: root.finalUrl, content: visible.slice(0, 600) },
            ],
          },
        ),
      );
    } else if (matched) {
      out.push(
        obs.info(
          G,
          'page.holding',
          `The phrase "${matched}" appears on the home page, but the page has substantial other content.`,
          { url: root.finalUrl, rawValue: { visibleLength: visible.length } },
        ),
      );
    }
  }

  // Empty-but-200 pages are a real and common failure.
  if (root.status < 300 && parsed && parsed.text.length < 60 && parsed.images.length === 0) {
    out.push(
      obs.issue(
        G,
        'page.empty',
        `The home page returned HTTP ${root.status} but contains almost no visible content (${parsed.text.length} characters).`,
        {
          url: root.finalUrl,
          rawValue: { textLength: parsed.text.length },
          evidence: [
            { kind: 'html_snippet', sourceUrl: root.finalUrl, content: (root.html ?? '').slice(0, 600) },
          ],
        },
      ),
    );
  }

  return out;
}
